USE DATABASE NYPD_DB;
USE SCHEMA RAW;

-- ==========================================
-- RAW TABLE
-- ==========================================

CREATE OR REPLACE TABLE MV_COLLISIONS_RAW (
CRASH_DATE DATE,
CRASH_TIME STRING,
BOROUGH STRING,
ZIP_CODE STRING,
LATITUDE FLOAT,
LONGITUDE FLOAT,
LOCATION STRING,
ON_STREET_NAME STRING,
CROSS_STREET_NAME STRING,
OFF_STREET_NAME STRING,
NUMBER_OF_PERSONS_INJURED INT,
NUMBER_OF_PERSONS_KILLED INT,
NUMBER_OF_PEDESTRIANS_INJURED INT,
NUMBER_OF_PEDESTRIANS_KILLED INT,
NUMBER_OF_CYCLIST_INJURED INT,
NUMBER_OF_CYCLIST_KILLED INT,
NUMBER_OF_MOTORIST_INJURED INT,
NUMBER_OF_MOTORIST_KILLED INT,
CONTRIBUTING_FACTOR_VEHICLE_1 STRING,
CONTRIBUTING_FACTOR_VEHICLE_2 STRING,
CONTRIBUTING_FACTOR_VEHICLE_3 STRING,
CONTRIBUTING_FACTOR_VEHICLE_4 STRING,
CONTRIBUTING_FACTOR_VEHICLE_5 STRING,
COLLISION_ID STRING,
VEHICLE_TYPE_CODE_1 STRING,
VEHICLE_TYPE_CODE_2 STRING,
VEHICLE_TYPE_CODE_3 STRING,
VEHICLE_TYPE_CODE_4 STRING,
VEHICLE_TYPE_CODE_5 STRING
);

-- ==========================================
-- LOAD DATA FROM STAGE
-- ==========================================

COPY INTO MV_COLLISIONS_RAW
FROM @NYPD_STAGE
FILE_FORMAT = NYPD_CSV_FORMAT;

-- Row Count
CREATE OR REPLACE TABLE ROW_COUNT AS
SELECT COUNT(*) AS TOTAL_ROWS
FROM MV_COLLISIONS_RAW;