USE DATABASE NYPD_DB;
USE SCHEMA RAW;

-- Missing Borough/Zip Count
CREATE OR REPLACE TABLE MISSING_BOROUGH_ZIP_COUNT AS
SELECT COUNT(*) AS MISSING_BOROUGH_ZIP
FROM MV_COLLISIONS_RAW
WHERE BOROUGH IS NULL OR ZIP_CODE IS NULL;

-- Latitude-Longitude Reference Table
CREATE OR REPLACE TABLE LAT_LONG_REF AS
SELECT DISTINCT
ROUND(LATITUDE) AS LATITUDE_INT,
ROUND(LONGITUDE) AS LONGITUDE_INT,
BOROUGH,
ZIP_CODE
FROM MV_COLLISIONS_RAW
WHERE BOROUGH IS NOT NULL
AND ZIP_CODE IS NOT NULL
AND LATITUDE IS NOT NULL
AND LONGITUDE IS NOT NULL;

-- Update Missing Values
UPDATE MV_COLLISIONS_RAW R
SET BOROUGH = L.BOROUGH,
    ZIP_CODE = L.ZIP_CODE
FROM LAT_LONG_REF L
WHERE ROUND(R.LATITUDE) = L.LATITUDE_INT
AND ROUND(R.LONGITUDE) = L.LONGITUDE_INT
AND (R.BOROUGH IS NULL OR R.ZIP_CODE IS NULL);

-- Cleaned Table
CREATE OR REPLACE TABLE CLEANED.MV_COLLISIONS_CLEAN AS
SELECT *
FROM MV_COLLISIONS_RAW
WHERE LATITUDE IS NOT NULL
AND LONGITUDE IS NOT NULL
AND BOROUGH IS NOT NULL
AND ZIP_CODE IS NOT NULL;