USE DATABASE NYPD_DB;

-- ==========================================
-- TOP 5 DAYS
-- ==========================================

CREATE OR REPLACE TABLE INSIGHTS.TOP5_DAYS AS
SELECT CRASH_DATE,
       BOROUGH,
       VEHICLE_TYPE_CODE_1,
       COUNT(*) AS ACCIDENT_COUNT
FROM CLEANED.MV_COLLISIONS_CLEAN
GROUP BY CRASH_DATE, BOROUGH, VEHICLE_TYPE_CODE_1
ORDER BY ACCIDENT_COUNT DESC
LIMIT 5;

-- ==========================================
-- BOROUGH MAX
-- ==========================================

CREATE OR REPLACE TABLE INSIGHTS.BOROUGH_MAX AS
WITH BOROUGH_TOTAL AS (
    SELECT BOROUGH, COUNT(*) AS TOTAL
    FROM CLEANED.MV_COLLISIONS_CLEAN
    GROUP BY BOROUGH
    ORDER BY TOTAL DESC
    LIMIT 1
)
SELECT C.BOROUGH, C.CRASH_DATE, COUNT(*) AS ACCIDENT_COUNT
FROM CLEANED.MV_COLLISIONS_CLEAN C
JOIN BOROUGH_TOTAL B
ON C.BOROUGH = B.BOROUGH
GROUP BY C.BOROUGH, C.CRASH_DATE
ORDER BY ACCIDENT_COUNT DESC
LIMIT 5;

-- ==========================================
-- TOP 5 VEHICLE TYPES
-- ==========================================

CREATE OR REPLACE TABLE INSIGHTS.TOP5_VEHICLE_TYPES AS
SELECT VEHICLE_TYPE_CODE_1,
       COUNT(*) AS ACCIDENT_COUNT
FROM CLEANED.MV_COLLISIONS_CLEAN
GROUP BY VEHICLE_TYPE_CODE_1
ORDER BY ACCIDENT_COUNT DESC
LIMIT 5;