-- Export CSV
COPY INTO @NYPD_STAGE/top5_days.csv
FROM INSIGHTS.TOP5_DAYS
FILE_FORMAT = (TYPE = CSV)
SINGLE = TRUE
OVERWRITE = TRUE
HEADER = TRUE;

COPY INTO @NYPD_STAGE/borough_max.csv
FROM INSIGHTS.BOROUGH_MAX
FILE_FORMAT = (TYPE = CSV)
SINGLE = TRUE
OVERWRITE = TRUE
HEADER = TRUE;

COPY INTO @NYPD_STAGE/top5_vehicle_types.csv
FROM INSIGHTS.TOP5_VEHICLE_TYPES
FILE_FORMAT = (TYPE = CSV)
SINGLE = TRUE
OVERWRITE = TRUE
HEADER = TRUE;