CREATE ROLE IF NOT EXISTS ANALYST;

CREATE OR REPLACE MASKING POLICY OFF_STREET_MASK
AS (VAL STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'ANALYST' THEN VAL
    ELSE '*********'
END;

ALTER TABLE CLEANED.MV_COLLISIONS_CLEAN
MODIFY COLUMN OFF_STREET_NAME
SET MASKING POLICY OFF_STREET_MASK;