USE DATABASE NYPD_DB;
USE SCHEMA CLEANED;

-- Vehicle Table (Demo)
CREATE OR REPLACE TABLE MV_COLLISIONS_VEHICLE (
VEHICLE_ID STRING,
STATE_REGISTRATION STRING,
VEHICLE_TYPE STRING,
VEHICLE_MAKE STRING,
VEHICLE_MODEL STRING,
VEHICLE_YEAR NUMBER,
TRAVEL_DIRECTION STRING,
VEHICLE_OCCUPANTS NUMBER,
DRIVER_SEX STRING,
DRIVER_LICENSE_STATUS STRING,
DRIVER_LICENSE_JURISDICTION STRING,
PRE_ACDNT_ACTION STRING
);

-- Secure View
CREATE OR REPLACE SECURE VIEW MV_VEHICLE_SHARE_VW AS
SELECT *
FROM MV_COLLISIONS_VEHICLE;

-- Share
CREATE OR REPLACE SHARE NYPD_VEHICLE_SHARE;

GRANT USAGE ON DATABASE NYPD_DB TO SHARE NYPD_VEHICLE_SHARE;
GRANT USAGE ON SCHEMA CLEANED TO SHARE NYPD_VEHICLE_SHARE;
GRANT SELECT ON VIEW MV_VEHICLE_SHARE_VW TO SHARE NYPD_VEHICLE_SHARE;